import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {api,write,message,Header,ErrorMessage,ConfirmAction} from './client';
import {statusLabels,type Customer,type Order,type OrderItem,type OrderListItem} from './types';
export function LoginPage(){
  const [customers,setCustomers]=useState<Customer[]>([]),[selected,setSelected]=useState(''),[pin,setPin]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
  useEffect(()=>{api<{customers:Customer[]}>('auth/customers').then(d=>setCustomers(d.customers)).catch(e=>setError(message(e))).finally(()=>setLoading(false));},[]);
  return <><Header active=""/><main className="login-page"><h1>攤位登入</h1><p>選店名，輸入 4 位 PIN。</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('auth/login',write('POST',{customerId:selected,pin}));const next=new URLSearchParams(location.search).get('next');location.assign(next&&(['/order','/my-orders'].includes(next)||/^\/receipt\/[a-f0-9-]{36}$/.test(next))?next:'/order');}catch(e){setError(message(e));}finally{setBusy(false);}}}>
    <label className="field">攤位／店名<select required disabled={busy||loading} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">請選擇</option>{customers.map(c=><option value={c.id} key={c.id}>{c.stallName}</option>)}</select></label>
    <label className="field">4 位 PIN<Input required type="password" autoComplete="current-password" inputMode="numeric" pattern="[0-9]{4}" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} disabled={busy}/></label><ErrorMessage error={error}/><Button type="submit" className="action" disabled={busy||!selected||pin.length!==4}>{busy?'登入中…':'登入'}</Button></form>
    <p className="small-hint">{!loading&&!customers.length?'尚未建立攤位，請洽管理者。':'忘記 PIN，請洽管理者重設。'}</p><p className="small-hint">測試版，請勿使用真實個資。</p></main></>;
}
export async function reorder(orderId:string){
  const data=await api<{items:OrderItem[];unavailable:OrderItem[];customerId:string}>(`orders/${orderId}/reorder`);
  sessionStorage.setItem('dm-reorder',JSON.stringify(data));sessionStorage.removeItem('dm-order-draft');sessionStorage.removeItem('dm-order-pending');location.assign('/order');
}
export function MyOrders(){
  const [orders,setOrders]=useState<OrderListItem[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[more,setMore]=useState(false),[busy,setBusy]=useState('');
  async function load(offset=0){setLoading(true);setError('');try{const d=await api<{orders:OrderListItem[];hasMore:boolean}>(`orders?offset=${offset}`);setOrders(old=>offset?[...old,...d.orders]:d.orders);setMore(d.hasMore);}catch(e){setError(message(e));}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  return <><Header active="order"/><main className="workspace"><div className="page-heading"><h1>我的訂單</h1><a className="large-link" href="/order">下單</a></div><ErrorMessage error={error}/><div className="order-cards">{orders.map(o=><article className="history-card" key={o.id}><div className="card-heading"><strong>{new Date(o.createdAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false})}</strong><span className={'status '+o.status}>{statusLabels[o.status!]}</span></div><p>{o.number}</p><p>共 {o.itemCount} 項商品</p>{o.fulfillmentConfirmation==='PENDING'&&<p className="warning-text">數量有異動，待您確認</p>}<div className="button-row"><a className="large-link" href={`/receipt/${o.id}`}>查看／修改</a><Button disabled={!!busy} onClick={async()=>{setBusy(o.id);try{await reorder(o.id);}catch(e){setError(message(e));setBusy('');}}}>{busy===o.id?'讀取中…':'再訂一次'}</Button></div></article>)}</div>{loading?<p role="status">讀取中…</p>:!orders.length?<div className="empty"><p>還沒有訂單</p><a href="/order">開始下單</a></div>:null}{more&&<Button variant="outline" disabled={loading} onClick={()=>load(orders.length)}>看更早訂單</Button>}</main></>;
}
export function OrderControls({order,onChange,onEditingChange}:{order:Order;onChange:(o:Order)=>void;onEditingChange:(editing:boolean)=>void}){
  const [editing,setEditing]=useState(false),[quantities,setQuantities]=useState<Record<string,number>>({}),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{onEditingChange(editing);const warn=(e:BeforeUnloadEvent)=>{if(editing){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[editing,onEditingChange]);
  async function refresh(){const d=await api<{order:Order}>(`orders/${order.id}`);onChange(d.order);setEditing(false);}
  if(!order.customerId)return <p className="small-hint no-print">舊訂單僅限原瀏覽器查看，未自動歸入任何攤位。</p>;
  return <section className="order-controls no-print"><div className="card-heading"><span className={'status '+order.status}>{statusLabels[order.status!]}</span><ConfirmAction label="更新" description={editing?'放棄尚未儲存的修改，重新讀取？':'重新讀取最新訂單？'} onConfirm={refresh}/></div><ErrorMessage error={error}/>
    {order.fulfillmentConfirmation==='PENDING'&&<div className="inline-confirm"><h2>數量有異動，待您確認</h2>{order.items.filter(i=>i.quantity>0).map(i=><p key={i.id}>{i.productName}：原訂 {i.quantity}，可配 {i.allocatedQuantity??'待確認'} {i.unit}</p>)}<ConfirmAction label="確認配貨數量" description="我已核對上方實際可配數量。" onConfirm={async()=>{const d=await api<{order:Order}>(`orders/${order.id}/acknowledge`,write('POST',{revision:order.revision,allocationRevision:order.allocationRevision}));onChange(d.order);}}/></div>}
    {order.fulfillmentConfirmation==='ACCEPTED'&&<p>已確認異動後配貨數量。</p>}
    {!editing&&<div className="button-row">{order.status==='SUBMITTED'&&<><Button variant="outline" onClick={()=>{setQuantities(Object.fromEntries(order.items.map(i=>[i.id!,i.quantity])));setNotes(order.notes);setEditing(true);}}>修改數量</Button><ConfirmAction label="取消訂單" description="取消後不再計入採購需求。確定取消？" onConfirm={async()=>{const d=await api<{order:Order}>(`orders/${order.id}/cancel`,write('POST',{revision:order.revision}));onChange(d.order);}}/></>}<Button disabled={busy} onClick={async()=>{setBusy(true);try{await reorder(order.id);}catch(e){setError(message(e));setBusy(false);}}}>再訂一次</Button></div>}
    {editing&&<form className="edit-order" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const d=await api<{order:Order}>(`orders/${order.id}`,write('PATCH',{revision:order.revision,notes,items:order.items.map(i=>({id:i.id,quantity:quantities[i.id!]}))}));onChange(d.order);setEditing(false);}catch(e){setError(message(e));}finally{setBusy(false);}}}><p>填 0 可移除此商品。</p>{order.items.map(i=><label className="edit-line" key={i.id}><span>{i.productName}<small>{i.specification}／{i.unit}</small></span><Input type="number" inputMode="numeric" min={0} max={9999} step={1} required value={quantities[i.id!]??0} disabled={busy} onChange={e=>setQuantities({...quantities,[i.id!]:Number(e.target.value)})}/></label>)}<label className="field">備註<textarea value={notes} maxLength={300} disabled={busy} onChange={e=>setNotes(e.target.value)}/></label><div className="button-row"><Button type="submit" disabled={busy}>儲存修改</Button><Button variant="outline" disabled={busy} onClick={()=>setEditing(false)}>返回</Button></div></form>}
    {!!order.history?.length&&<details className="history-detail"><summary>修改紀錄</summary>{order.history.map(h=><div key={h.revision}><strong>{({SUBMITTED:'建立訂單',EDITED:'修改數量',CANCELLED:'取消',LOCKED:'截單',PURCHASING:'建立採購',ALLOCATION_PROPOSED:'配貨異動',ALLOCATION_ACCEPTED:'確認配貨',COMPLETED:'完成'} as Record<string,string>)[h.kind]||h.kind}</strong><p>{new Date(h.createdAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})} · {h.source.startsWith('CUSTOMER')?'攤位操作':'管理者操作'}</p>{h.kind==='EDITED'&&(()=>{const before=JSON.parse(h.before),after=JSON.parse(h.after);return (after.items as OrderItem[]).map(i=><p key={i.id}>{i.productName}：{(before.items as OrderItem[]).find(j=>j.id===i.id)?.quantity??0} → {i.quantity} {i.unit}</p>);})()}</div>)}</details>}
  </section>;
}
