import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {api,write,message,ErrorMessage,ConfirmAction,ClientError} from './client';
import {taipeiDay,statusLabels,type Customer,type Order,type OrderListItem,type BatchItem,type PurchaseBatch} from './types';

function AdminLogin({onLogin}:{onLogin:()=>void}){
  const [secret,setSecret]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  return <main className="login-page"><a href="/">回首頁</a><h1>管理者登入</h1><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('auth/admin-login',write('POST',{secret}));setSecret('');onLogin();}catch(e){setError(message(e));}finally{setBusy(false);}}}><label className="field">管理密碼<Input type="password" autoComplete="current-password" value={secret} disabled={busy} onChange={e=>setSecret(e.target.value)} required/></label><ErrorMessage error={error}/><Button type="submit" className="action" disabled={busy}>登入管理</Button></form><p className="small-hint">請使用獨立管理密碼，不是攤位 PIN。</p></main>;
}
function AdminHeader(){
  const [error,setError]=useState('');return <div className="admin-header no-print"><a href="/">東門市場</a><nav><a href="/admin/orders">訂單／截單</a><a href="/admin/purchasing">集中採購</a></nav><Button variant="outline" onClick={async()=>{try{await api('auth/admin-logout',write('POST',{}));location.assign('/admin/orders');}catch(e){setError(message(e));}}}>登出</Button><ErrorMessage error={error}/></div>;
}
function CustomersPanel(){
  const [customers,setCustomers]=useState<Customer[]>([]),[stallName,setStallName]=useState(''),[pin,setPin]=useState(''),[reset,setReset]=useState(''),[newPin,setNewPin]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  async function load(){try{setCustomers((await api<{customers:Customer[]}>('admin/customers')).customers);}catch(e){setError(message(e));}}
  useEffect(()=>{void load();},[]);
  return <details className="customer-panel"><summary>攤位管理／設定 PIN</summary><p>由管理者建立，PIN 請當面交給攤位。測試請用假名。</p><ErrorMessage error={error}/>{notice&&<p role="status">{notice}</p>}<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('admin/customers',write('POST',{stallName,pin}));setStallName('');setPin('');setNotice('攤位已建立，請交付 PIN。');await load();}catch(e){setError(message(e));}finally{setBusy(false);}}}><label className="field">新增攤位<Input required value={stallName} maxLength={60} disabled={busy} onChange={e=>setStallName(e.target.value)}/></label><label className="field">4 位 PIN<Input type="password" autoComplete="new-password" required inputMode="numeric" pattern="[0-9]{4}" maxLength={4} value={pin} disabled={busy} onChange={e=>setPin(e.target.value.replace(/\D/g,''))}/></label><Button type="submit" disabled={busy}>建立攤位</Button></form>
    {customers.map(c=><div className="customer-row" key={c.id}><strong>{c.stallName} {!c.active&&'（停用）'}</strong><div className="button-row"><Button variant="outline" onClick={()=>{setReset(c.id);setNewPin('');}}>重設 PIN</Button><ConfirmAction label={c.active?'停用':'啟用'} description="此操作會登出該攤位的所有裝置。" onConfirm={async()=>{await api(`admin/customers/${c.id}`,write('PATCH',{active:!c.active}));await load();}}/></div>{reset===c.id&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api(`admin/customers/${c.id}`,write('PATCH',{pin:newPin}));setNewPin('');setReset('');setNotice('PIN 已更新，原登入已失效。');}catch(e){setError(message(e));}finally{setBusy(false);}}}><label className="field">新 PIN<Input required type="password" autoComplete="new-password" inputMode="numeric" pattern="[0-9]{4}" maxLength={4} value={newPin} onChange={e=>setNewPin(e.target.value.replace(/\D/g,''))}/></label><Button type="submit" disabled={busy}>儲存新 PIN</Button></form>}</div>)}
  </details>;
}
function AdminOrderDetails({id}:{id:string}){
  const [order,setOrder]=useState<Order|null>(null),[error,setError]=useState('');
  return <details className="history-detail" onToggle={e=>{if(e.currentTarget.open&&!order)api<{order:Order}>(`admin/orders/${id}`).then(d=>setOrder(d.order)).catch(e=>setError(message(e)));}}><summary>商品／修改紀錄</summary><ErrorMessage error={error}/>{order?.items.map(i=><p key={i.id}>{i.productName} {i.specification}：{i.quantity} {i.unit}{i.originalQuantity!==i.quantity&&`（原訂 ${i.originalQuantity}）`}{i.allocatedQuantity!=null&&`，配 ${i.allocatedQuantity}`}</p>)}{order?.notes&&<p>備註：{order.notes}</p>}{order?.history?.map(h=><div key={h.revision}><p>第 {h.revision} 版 · {h.source.startsWith('CUSTOMER')?'攤位':'管理者'} · {new Date(h.createdAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})}</p>{h.kind==='EDITED'&&(()=>{const a=JSON.parse(h.after),b=JSON.parse(h.before);return (a.items as Order['items']).map(i=><p key={i.id}>{i.productName}：{(b.items as Order['items']).find(j=>j.id===i.id)?.quantity??0} → {i.quantity}</p>);})()}</div>)}</details>;
}
function useOrders(){
  const [orders,setOrders]=useState<OrderListItem[]>([]),[from,setFrom]=useState(taipeiDay()),[to,setTo]=useState(taipeiDay()),[error,setError]=useState(''),[loading,setLoading]=useState(false),[hasMore,setMore]=useState(false);
  async function load(offset=0){setLoading(true);setError('');try{const d=await api<{orders:OrderListItem[];hasMore:boolean}>(`admin/orders?from=${from}&to=${to}&offset=${offset}`);setOrders(old=>offset?[...old,...d.orders]:d.orders);setMore(d.hasMore);}catch(e){setError(message(e));}finally{setLoading(false);}}
  useEffect(()=>{void load();/* Initial date is today; filters apply on explicit submit. */},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const filter=<form className="admin-filter" onSubmit={e=>{e.preventDefault();void load();}}><label>從<Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>至<Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><Button disabled={loading} type="submit">查詢／更新</Button></form>;
  return {orders,loading,error,setError,load,filter,hasMore};
}
function AdminOrders(){
  const data=useOrders(),[selected,setSelected]=useState<Record<string,number>>({}),[notice,setNotice]=useState('');
  const candidates=data.orders.filter(o=>o.customerId&&o.status==='SUBMITTED');
  useEffect(()=>setSelected({}),[data.orders]);
  return <main className="workspace"><h1>訂單／截單</h1><CustomersPanel/>{data.filter}<ErrorMessage error={data.error}/>{notice&&<p role="status">{notice}</p>}<div className="button-row"><Button variant="outline" onClick={()=>setSelected(Object.fromEntries(candidates.map(o=>[o.id,o.revision!])))}>全選可截單</Button><Button variant="outline" onClick={()=>setSelected({})}>取消選取</Button></div><div className="order-cards">{data.orders.map(o=><article className="history-card" key={o.id}><label className="order-check"><input type="checkbox" disabled={!o.customerId||o.status!=='SUBMITTED'} checked={!!selected[o.id]} onChange={e=>setSelected(old=>{const next={...old};if(e.target.checked)next[o.id]=o.revision!;else delete next[o.id];return next;})}/><strong>{o.stall}</strong><span className={'status '+o.status}>{statusLabels[o.status!]}</span></label><p>{o.number}</p><p>{new Date(o.createdAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})} · {o.itemCount} 項</p>{o.fulfillmentConfirmation==='PENDING'&&<p className="warning-text">數量有異動，待客戶確認</p>}{!o.customerId&&<p>舊訂單尚未歸戶，僅供查閱，不可進入新採購批次。</p>}<AdminOrderDetails id={o.id}/></article>)}</div>{data.loading&&<p>讀取中…</p>}{!data.loading&&!data.orders.length&&<p className="empty">此期間沒有訂單</p>}{data.hasMore&&<Button onClick={()=>data.load(data.orders.length)}>載入更多訂單</Button>}<div className="admin-action"><ConfirmAction label={`截單（${Object.keys(selected).length} 張）`} disabled={!Object.keys(selected).length} description="選取的訂單將鎖定，攤位不能再自行修改。" onConfirm={async()=>{const d=await api<{locked:number}>('admin/cutoff',write('POST',{orders:Object.entries(selected).map(([id,revision])=>({id,revision}))}));setNotice(`已截單 ${d.locked} 張。請到集中採購建立批次。`);await data.load();}}/></div></main>;
}
function DemandCard({item}:{item:BatchItem}){return <article className="purchase-card"><h2>{item.productName}</h2><p>{item.specification}</p><strong className="demand">需求 {item.requestedQuantity} {item.unit}</strong><div className="allocation-rows">{item.allocations.map(a=><p key={a.id}><span>{a.stall}</span><b>{a.requestedQuantity} {item.unit}</b></p>)}</div></article>;}
function Purchasing(){
  const data=useOrders(),[selected,setSelected]=useState<Record<string,number>>({}),[preview,setPreview]=useState<BatchItem[]>([]),[batches,setBatches]=useState<PurchaseBatch[]>([]),[busy,setBusy]=useState(false),[key,setKey]=useState('');
  useEffect(()=>{api<{batches:PurchaseBatch[]}>('admin/purchasing').then(d=>setBatches(d.batches)).catch(e=>data.setError(message(e)));},[]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{setSelected({});setPreview([]);},[data.orders]);
  const locked=data.orders.filter(o=>o.customerId&&o.status==='LOCKED');const selection=Object.entries(selected).map(([id,revision])=>({id,revision}));
  return <main className="workspace"><h1>集中採購</h1><p>選已截單訂單，核對各攤需求。</p>{data.filter}<ErrorMessage error={data.error}/><div className="button-row"><Button variant="outline" disabled={busy} onClick={()=>{setSelected(Object.fromEntries(locked.map(o=>[o.id,o.revision!])));setPreview([]);}}>全選已截單</Button><Button variant="outline" disabled={busy} onClick={()=>{setSelected({});setPreview([]);}}>取消選取</Button></div>{locked.map(o=><label className="purchase-order-choice" key={o.id}><input type="checkbox" disabled={busy} checked={!!selected[o.id]} onChange={e=>{setSelected(old=>{const n={...old};if(e.target.checked)n[o.id]=o.revision!;else delete n[o.id];return n;});setPreview([]);}}/><span><strong>{o.stall}</strong><small>{o.number} · {o.itemCount} 項</small></span></label>)}{!locked.length&&!data.loading&&<p className="empty">沒有待採購訂單，請先到訂單頁截單。</p>}{data.hasMore&&<Button onClick={()=>data.load(data.orders.length)}>載入更多訂單</Button>}<Button disabled={busy||!selection.length} onClick={async()=>{setBusy(true);data.setError('');try{const d=await api<{items:BatchItem[]}>('admin/purchasing/preview',write('POST',{orders:selection}));setPreview(d.items);setKey(crypto.randomUUID());}catch(e){data.setError(message(e));}finally{setBusy(false);}}}>核對採購需求</Button><div className="purchase-grid">{preview.map(i=><DemandCard key={i.id} item={i}/>)}</div>{preview.length>0&&<ConfirmAction label="建立本次採購批次" disabled={busy} description={`將 ${selection.length} 張訂單加入同一採購批次，不會自動傳送給供應商。`} onConfirm={async()=>{setBusy(true);try{const d=await api<{batch:PurchaseBatch}>('admin/purchasing',write('POST',{orders:selection,idempotencyKey:key}));location.assign(`/admin/purchasing/${d.batch.id}`);}finally{setBusy(false);}}}/>}<h2 className="section-title">已建立批次</h2><div className="order-cards">{batches.map(b=><a className="history-card" key={b.id} href={`/admin/purchasing/${b.id}`}><strong>{b.number}</strong><p>{b.status==='COMPLETED'?'已完成':b.status==='SUPPLIER_CONFIRMED'?'已確認供貨':'待填供應量'}</p><span>開啟配貨 →</span></a>)}</div></main>;
}
type Draft={id:string;supplierConfirmedQuantity:number|null;allocations:{id:string;allocatedQuantity:number}[]}[];
const batchDraft=(b:PurchaseBatch):Draft=>b.items.map(i=>({id:i.id,supplierConfirmedQuantity:i.supplierConfirmedQuantity,allocations:i.allocations.map(a=>({id:a.id,allocatedQuantity:i.supplierConfirmedQuantity===null?a.requestedQuantity:a.allocatedQuantity}))}));
function BatchDetails({id,printView}:{id:string;printView?:string}){
  const [batch,setBatch]=useState<PurchaseBatch|null>(null),[draft,setDraft]=useState<Draft>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  function apply(b:PurchaseBatch){setBatch(b);setDraft(batchDraft(b));}
  async function load(){try{apply((await api<{batch:PurchaseBatch}>(`admin/purchasing/${id}`)).batch);}catch(e){setError(message(e));}}
  useEffect(()=>{void load();},[id]); // eslint-disable-line react-hooks/exhaustive-deps
  const dirty=!!batch&&JSON.stringify(draft)!==JSON.stringify(batchDraft(batch));
  useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  if(!batch)return <main className="workspace"><p>讀取中…</p><ErrorMessage error={error}/></main>;
  if(printView)return <main className="workspace"><div className="button-row no-print"><a className="large-link" href={`/admin/purchasing/${id}`}>回配貨</a><Button disabled={batch.status==='PURCHASING'} onClick={()=>window.print()}>列印／另存 PDF</Button></div>{batch.status==='PURCHASING'?<p>請先儲存供應與配貨確認。</p>:<article className="batch-print receipt-sheet"><h1>{printView==='supplier'?'供應商採購單':'各攤配貨單'}</h1><p>{batch.number} · 第 {batch.revision} 版</p><p>{batch.demo?'測試文件，不會實際採購。':''}</p>{printView==='supplier'?<table><thead><tr><th>商品</th><th>規格</th><th>單位</th><th>採購確認數量</th></tr></thead><tbody>{batch.items.map(i=><tr key={i.id}><td>{i.productName}</td><td>{i.specification}</td><td>{i.unit}</td><td>{i.supplierConfirmedQuantity}</td></tr>)}</tbody></table>:batch.items.map(i=><section key={i.id}><h2>{i.productName} · {i.specification}</h2><p>總供應量 {i.supplierConfirmedQuantity} {i.unit}</p><table><thead><tr><th>攤位</th><th>原需求</th><th>分配量</th><th>確認</th></tr></thead><tbody>{i.allocations.map(a=><tr key={a.id}><td>{a.stall}</td><td>{a.requestedQuantity}</td><td>{a.allocatedQuantity} {i.unit}</td><td>{batch.orders.find(o=>o.id===a.orderId)?.fulfillmentConfirmation==='PENDING'?'待確認':'已核對'}</td></tr>)}</tbody></table></section>)}</article>}</main>;
  const valid=draft.every(i=>i.supplierConfirmedQuantity!==null&&Number.isInteger(i.supplierConfirmedQuantity)&&i.allocations.reduce((sum,a)=>sum+a.allocatedQuantity,0)===i.supplierConfirmedQuantity&&i.allocations.every(a=>Number.isInteger(a.allocatedQuantity)&&a.allocatedQuantity>=0));
  return <main className="workspace"><a className="large-link" href="/admin/purchasing">回採購清單</a><div className="page-heading"><div><h1>供應／配貨</h1><p>{batch.number}</p></div><ConfirmAction label="更新" disabled={busy} description={dirty?'放棄尚未儲存的配貨變更，重新讀取？':'重新讀取最新供應與配貨資料？'} onConfirm={load}/></div><ErrorMessage error={error}/>{notice&&<p role="status">{notice}</p>}{batch.demo===1&&<p className="demo-notice">測試批次，不會實際採購。</p>}
    <div className="purchase-grid">{batch.items.map((item,index)=>{const d=draft[index],allocated=d.allocations.reduce((s,a)=>s+a.allocatedQuantity,0),supply=d.supplierConfirmedQuantity;return <article className="purchase-card" key={item.id}><h2>{item.productName}</h2><p>{item.specification}／{item.unit}</p><strong className="demand">需求 {item.requestedQuantity}</strong><label className="field">供應商可供<Input type="number" min={0} max={item.requestedQuantity} step={1} inputMode="numeric" value={supply??''} disabled={busy||batch.status==='COMPLETED'} onChange={e=>setDraft(old=>old.map((x,n)=>n===index?{...x,supplierConfirmedQuantity:e.target.value===''?null:Number(e.target.value)}:x))}/></label><p className="warning-text">短缺：{supply===null?'待填供應量':Math.max(0,item.requestedQuantity-supply)}</p>{item.allocations.map((a,ai)=><label className="edit-line" key={a.id}><span>{a.stall}<small>需求 {a.requestedQuantity} {item.unit}</small></span><Input type="number" aria-label={`${a.stall}${item.productName}配貨量`} min={0} max={a.requestedQuantity} step={1} inputMode="numeric" value={d.allocations[ai].allocatedQuantity} disabled={busy||batch.status==='COMPLETED'} onChange={e=>setDraft(old=>old.map((x,n)=>n===index?{...x,allocations:x.allocations.map((v,k)=>k===ai?{...v,allocatedQuantity:Number(e.target.value)}:v)}:x))}/></label>)}<p className={supply!==allocated?'warning-text':'allocation-total'}>已配 {allocated}／可供 {supply??'未填'}</p></article>;})}</div>
    {batch.status!=='COMPLETED'&&<ConfirmAction label="儲存供應與配貨確認" disabled={busy||!valid} description="請核對所有攤位配貨量。短配訂單會要求客戶確認；重新配貨後需重新確認。" onConfirm={async()=>{setBusy(true);setError('');try{const d=await api<{batch:PurchaseBatch}>(`admin/purchasing/${id}/confirm`,write('POST',{revision:batch.revision,items:draft}));apply(d.batch);setNotice('配貨已儲存。請提醒短配攤位登入「我的訂單」確認。');}finally{setBusy(false);}}}/>}
    {!valid&&batch.status!=='COMPLETED'&&<p className="small-hint">請填可供量，並把數量分配完成。</p>}<div className="order-cards">{batch.orders.map(o=><div className="history-card" key={o.id}><strong>{o.stall}</strong><p>{o.fulfillmentConfirmation==='PENDING'?'數量有異動，待客戶確認':o.fulfillmentConfirmation==='ACCEPTED'?'客戶已確認異動':batch.status==='PURCHASING'?'待確認供貨':'依原需求配貨'}</p></div>)}</div>
    {dirty&&<p className="warning-text">有尚未儲存的配貨變更，請先儲存再列印或完成。</p>}{batch.status!=='PURCHASING'&&!dirty&&<div className="button-row"><a className="large-link" href={`/admin/purchasing/${id}/print?view=supplier`}>供應商採購列印</a><a className="large-link" href={`/admin/purchasing/${id}/print?view=allocation`}>各攤配貨列印</a></div>}{batch.status==='SUPPLIER_CONFIRMED'&&<ConfirmAction label="完成本次批次" disabled={busy||dirty||batch.orders.some(o=>o.fulfillmentConfirmation==='PENDING')} description="確認已完成交貨。完成後不可修改本批配貨。" onConfirm={async()=>{const d=await api<{batch:PurchaseBatch}>(`admin/purchasing/${id}/complete`,write('POST',{revision:batch.revision}));apply(d.batch);}}/>}{batch.status==='COMPLETED'&&<p className="status">本次批次已完成</p>}
  </main>;
}
export function AdminPortal(){
  const [allowed,setAllowed]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{api<{admin:boolean}>('auth/me').then(d=>setAllowed(d.admin)).catch(e=>{if(!(e instanceof ClientError))setError(message(e));}).finally(()=>setLoading(false));},[]);
  if(loading)return <main className="workspace">讀取中…</main>;if(error)return <main className="workspace"><ErrorMessage error={error}/></main>;if(!allowed)return <AdminLogin onLogin={()=>setAllowed(true)}/>;
  const path=location.pathname,parts=path.split('/'),print=parts[4]==='print';return <><AdminHeader/>{path==='/admin'||path==='/admin/orders'?<AdminOrders/>:path==='/admin/purchasing'?<Purchasing/>:parts[2]==='purchasing'&&parts[3]?<BatchDetails id={parts[3]} printView={print?(new URLSearchParams(location.search).get('view')==='supplier'?'supplier':'allocation'):undefined}/>:<main className="workspace">找不到管理頁面</main>}</>;
}
